name: Windows (clang-cl + Ninja)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]
        include:
          - config: Debug
            configure_preset: win-clangcl-debug
            build_preset: build-debug
          - config: Release
            configure_preset: win-clangcl-release
            build_preset: build-release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # MSVC environment (Windows SDK + lib paths)
      - name: MSVC env
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      # LLVM/Clang-CL >=19 required by MSVC STL v14.44 (use 21 to match local)
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v2.0.8
        with:
          version: "21.1.3"
          directory: "C:\\LLVM"

      - name: Add LLVM to PATH
        run: echo "C:\\LLVM\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Show versions
        run: |
          clang-cl --version
          cmake --version
          ninja --version

      # Configure using CMakePresets.json
      - name: Configure (${{ matrix.config }})
        run: cmake --preset ${{ matrix.configure_preset }}

      # Guard: ensure clang-cl is actually selected
      - name: Verify compiler selection
        shell: pwsh
        run: |
          $vars = cmake -LA -N "out/build/${{ matrix.configure_preset }}"
          $cxx = ($vars | Select-String 'CMAKE_CXX_COMPILER:.*').ToString()
          Write-Host "CMAKE_CXX_COMPILER => $cxx"
          if ($cxx -notmatch 'clang-cl\.exe') {
            Write-Error "CMAKE_CXX_COMPILER is not clang-cl.exe"
            exit 1
          }

      # Build with presets (Ninja)
      - name: Build (${{ matrix.config }})
        run: cmake --build --preset ${{ matrix.build_preset }}

      # Package artifacts (EXE + DLL + LIB) and create checksums
      - name: Package artifacts
        run: |
          New-Item -Force -ItemType Directory artifact | Out-Null
          Copy-Item out\build\${{ matrix.configure_preset }}\bin\lbw_bootstrap.exe artifact\
          Copy-Item out\build\${{ matrix.configure_preset }}\bin\ladybird_platform_windows.dll artifact\
          Copy-Item out\build\${{ matrix.configure_preset }}\lib\ladybird_platform_windows.lib artifact\
          Get-FileHash artifact\lbw_bootstrap.exe -Algorithm SHA256 | ForEach-Object { $_.Hash + " *lbw_bootstrap.exe" } | Out-File artifact\SHA256SUMS.txt -Encoding ascii
          Get-FileHash artifact\ladybird_platform_windows.dll -Algorithm SHA256 | ForEach-Object { $_.Hash + " *ladybird_platform_windows.dll" } | Add-Content artifact\SHA256SUMS.txt -Encoding ascii
          Get-FileHash artifact\ladybird_platform_windows.lib -Algorithm SHA256 | ForEach-Object { $_.Hash + " *ladybird_platform_windows.lib" } | Add-Content artifact\SHA256SUMS.txt -Encoding ascii

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lbw-${{ matrix.config }}-windows
          path: artifact
          retention-days: 14
